INSERT INTO burgers (name) VALUES ("Cauliflower's Cumin From Inside the House");
INSERT INTO burgers (name) VALUES ("Silentil Night");
INSERT INTO burgers (name) VALUES ("Poblano Picasso");
INSERT INTO burgers (name) VALUES ("Beets of Burden");
INSERT INTO burgers (name) VALUES ("Don't You Four Cheddar 'Bout Me");
INSERT INTO burgers (name) VALUES ("Paranormal Pepper Jack-tivity");
INSERT INTO burgers (name) VALUES ("Let's Give 'Em Something Shiitake 'Bout");
INSERT INTO burgers (name) VALUES ("Kale Mary");
INSERT INTO burgers (name) VALUES ("Little Swiss Bunshine");
INSERT INTO burgers (name) VALUES ("Bohemian Radishy");
INSERT INTO burgers (name) VALUES ("Tarragon in Sixty Seconds");
INSERT INTO burgers (name) VALUES ("Thank God It's Fried Egg");
INSERT INTO burgers (name) VALUES ("A Leek of Their Own");
INSERT INTO burgers (name) VALUES ("Sweet Chili O’Mine");
INSERT INTO burgers (name) VALUES ("Hit Me With Your Best Shallot");
INSERT INTO burgers (name) VALUES ("Sympathy for the Deviled Egg");
INSERT INTO burgers (name) VALUES ("Something's NOT Fishy");
INSERT INTO burgers (name) VALUES ("Bean Spirit");
INSERT INTO burgers (name) VALUES ("Sweet Home Avocado");
INSERT INTO burgers (name) VALUES ("Yes I Cayenne");
